import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { Store } from '../server/store.js';
import { DanmakuFonts, fontMetadata, MAX_FONT_BYTES } from '../server/danmaku-font.js';
import { assText } from '../server/media.js';
import { createApp } from '../server/index.js';
function font(family='Test Font',advance=1000){
  const name=Buffer.from(family,'utf16le').swap16(),table=Buffer.alloc(18+name.length);table.writeUInt16BE(1,2);table.writeUInt16BE(18,4);table.writeUInt16BE(3,6);table.writeUInt16BE(1,8);table.writeUInt16BE(0x409,10);table.writeUInt16BE(1,12);table.writeUInt16BE(name.length,14);name.copy(table,18);
  const head=Buffer.alloc(54),hhea=Buffer.alloc(36);head.writeUInt16BE(1000,18);hhea.writeUInt16BE(advance,10);
  const tags=['name','cmap','head','maxp','glyf','hhea'],header=Buffer.alloc(12+tags.length*16);header.writeUInt32BE(0x10000);header.writeUInt16BE(tags.length,4);let offset=header.length;const data=[table,Buffer.alloc(4),head,Buffer.alloc(6),Buffer.alloc(4),hhea];
  for(let i=0;i<tags.length;i++){header.write(tags[i],12+i*16);header.writeUInt32BE(offset,20+i*16);header.writeUInt32BE(data[i].length,24+i*16);offset+=data[i].length;}return Buffer.concat([header,...data]);
}
async function setup(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'caibo-font-test-')),store=new Store(root);t.after(async()=>{store.close();await fs.rm(root,{recursive:true,force:true});});return {root,store,fonts:new DanmakuFonts(store)};}
test('字体名来自文件而非文件名，中文字体名安全用于 ASS',()=>{assert.equal(fontMetadata(font('测试字体')).family,'测试字体');assert.match(assText([{time:0,text:'hello'}],640,360,fontMetadata(font('测试字体'))),/Style: Default,测试字体,/);});
test('宽字体的水平度量用于避让并随选择保留',async t=>{const {fonts}=await setup(t),selected=await fonts.import(font('Wide Font',3000));assert.ok(selected.advanceRatio>3);assert.equal(fonts.snapshot().advanceRatio,selected.advanceRatio);assert.equal((await fonts.selection(selected.id)).advanceRatio,selected.advanceRatio);});
test('旧式 Mac 名称表的 ASCII 字体名也可导入',()=>{const bytes=font('AppleGothic'),nameOffset=bytes.readUInt32BE(20);bytes.writeUInt16BE(1,nameOffset+6);bytes.writeUInt16BE(0,nameOffset+8);bytes.writeUInt16BE(0,nameOffset+10);bytes.writeUInt16BE(11,nameOffset+14);bytes.write('AppleGothic',nameOffset+18);assert.equal(fontMetadata(bytes).family,'AppleGothic');});
test('拒绝无效格式、表越界、超大文件和 ASS 名称注入',()=>{for(const bytes of [Buffer.from('not font'),Buffer.alloc(MAX_FONT_BYTES+1),font('bad,Default'),font('x\nInjected')])assert.throws(()=>fontMetadata(bytes));const bytes=font();bytes.writeUInt32BE(0xffffffff,20);assert.throws(()=>fontMetadata(bytes));});
test('导入拷贝并持久保存，重设默认不破坏正在导出的字体快照',async t=>{const {fonts,store,root}=await setup(t);const selected=await fonts.import(font('Preview Font'));assert.equal(new DanmakuFonts(store).selected().id,selected.id);const work=path.join(root,'work');await fs.mkdir(work);fonts.reset();const relative=await fonts.stage(selected,work);assert.deepEqual(await fs.readFile(path.join(work,relative,'danmaku.ttf')),font('Preview Font'));assert.equal(fonts.selected(),null);});
test('草稿字体可读取和预览，但只有手动保存才更改当前字体',async t=>{const {fonts,store}=await setup(t);const current=await fonts.import(font('Current'));const draft=await fonts.import(font('Draft'),{select:false});assert.equal(fonts.snapshot().id,current.id);assert.equal((await fonts.selection(draft.id)).family,'Draft');assert.equal(fonts.snapshot().id,current.id);store.setting('danmaku-font',await fonts.selection(draft.id));assert.equal(fonts.snapshot().id,draft.id);});
test('导入拒绝符号链接目录，读取拒绝被篡改字体',async t=>{const {fonts,root}=await setup(t);const selected=await fonts.import(font());const file=await fonts.file(selected);await fs.writeFile(file,font('Changed'));await assert.rejects(fonts.file(selected),/校验失败/);await fs.rm(fonts.root,{recursive:true});const outside=path.join(root,'outside');await fs.mkdir(outside);try{await fs.symlink(outside,fonts.root,process.platform==='win32'?'junction':'dir');}catch(e){if(['EPERM','EACCES'].includes(e.code)){t.skip('No link privilege');return;}throw e;}await assert.rejects(fonts.import(font()),/目录异常/);assert.deepEqual(await fs.readdir(outside),[]);});
test('真实 API 导入、字体响应 MIME、恢复默认与跨站阻断',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'caibo-font-api-'));const app=await createApp({data:root,noRecorder:true,ffmpeg:'unused',ffprobe:'unused',compact:false,preparation:false});t.after(async()=>{await app.close();await fs.rm(root,{recursive:true,force:true});});const url=`http://127.0.0.1:${app.port}`;let response=await fetch(url+'/api/danmaku-font',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:font()});assert.equal(response.status,200);const {font:selected}=await response.json();response=await fetch(url+selected.url);assert.equal(response.headers.get('content-type'),'font/ttf');assert.deepEqual(Buffer.from(await response.arrayBuffer()),font());response=await fetch(url+'/api/danmaku-font',{method:'POST',headers:{Origin:'https://outside.invalid','Content-Type':'application/octet-stream'},body:font('Other')});assert.equal(response.status,403);assert.equal(app.snapshot().danmakuFont.id,selected.id);response=await fetch(url+'/api/danmaku-font',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reset:true})});assert.equal((await response.json()).font,null);});
